# Generated by Django 5.2.17 on 2026-08-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titel',
            new_name='title',
        ),
    ]
