# Generated by Django 5.2.17 on 2026-09-01 23:51

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    post = apps.get_model('blog', 'post')
    used_slugs = set()

    for item in post.objects.order_by('pk'):
        base_slug = slugify(item.title) or f'post-{item.pk}'
        candidate = base_slug
        suffix = 2
        while candidate in used_slugs:
            candidate = f'{base_slug}-{suffix}'
            suffix += 1
        item.slug = candidate
        item.save(update_fields=['slug'])
        used_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_at_post_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('python', 'python'), ('backend', 'backend'), ('django', 'django'), ('git', 'git')], default='python', max_length=100),
        ),
    ]
